spring:
  application:
    name: TaskFlowDesigner
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           # 指定数据源
    initialSize: 5
    minIdle: 5
    maxActive: 20 
    maxWait: 60000  
    filters: stat
    minEvictableIdleTimeMillis: 300000    # 配置一个连接在池中最小生存的时间，单位是毫秒
    poolPreparedStatements: true
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.itmuch.youran.persistence: ERROR
